### PR TITLE
issue 14

### LINKED ISSUE #14: Change in register user api
new register api should take email id, name (first and last) , phone and a file ( any format ..for reference the is a file uploading api in this project check that out for multipart request ) 

you have to store all the details except the file , we have to  hash the file and will store the hash only in data base, no need to salt for now, use SHA-256 .

### PR DESCRIPTION
**Pull request by Anurag-ravi**
## Issue
Fixes #14 

## Description

Implemented register api which takes first name, last name, email(unique) , phone no. , file
then hashes the file using sha256 and saves all data along with hash in database except the uploaded file

### CODE REVIEW

**Review by RupakBiswas-2304 — COMMENTED** [review]
You have done some nice changes, but it does not solves the bug ..the server still not reciving the jwt cookie.

**Comment by Anurag-ravi** [comment]
I tried this
when i switched to previous commit where the user model was previous one, then i was getting jwt token in frontend as cookies and was able to make request to server for fetching user details
but after implementing register api, i had to change the user model a little bit
and after that jwt token is again not being received

**Review by RupakBiswas-2304 — CHANGES_REQUESTED** [review]
This is working well, still i suggest some changes 

you created some new column f_name and l_name 
but there was already first_name and last_name 
so either delete the previos one or the new one
also delete the password feild .. we dont need that 

also  while creating pull request  add you name in auther section of readme.md

**Comment by RupakBiswas-2304** [comment]
> I tried this when i switched to previous commit where the user model was previous one, then i was getting jwt token in frontend as cookies and was able to make request to server for fetching user details but after implementing register api, i had to change the user model a little bit and after that jwt token is again not being received

@Anurag-ravi  change the requested I will merge than u can work on that bug again , these are 2 different issue though,

**Comment by Anurag-ravi** [comment]
> This is working well, still i suggest some changes
> 
> you created some new column f_name and l_name but there was already first_name and last_name so either delete the previos one or the new one also delete the password feild .. we dont need that
> 
> also while creating pull request add you name in auther section of readme.md

i think there was only name field in user model previously, later i removed it and added 2 new fields, f_name,l_name
also i have removed password field 
can you explain further?

**Comment by RupakBiswas-2304** [comment]
> > This is working well, still i suggest some changes
> > you created some new column f_name and l_name but there was already first_name and last_name so either delete the previos one or the new one also delete the password feild .. we dont need that
> > also while creating pull request add you name in auther section of readme.md
> 
> i think there was only name field in user model previously, later i removed it and added 2 new fields, f_name,l_name also i have removed password field can you explain further?

image

**Comment by RupakBiswas-2304** [comment]
I think this is coming by default from some where ..

**Comment by Anurag-ravi** [comment]
> I think this is coming by default from some where ..

ohh, I got it
i will create a pr with those fields removed

**Comment by Anurag-ravi** [comment]
> > I think this is coming by default from some where ..
> 
> ohh, I got it i will update this pr with those fields removed

done

**Comment by RupakBiswas-2304** [comment]
Thank you @Anurag-ravi

**Comment by Anurag-ravi** [comment]
> > I tried this when i switched to previous commit where the user model was previous one, then i was getting jwt token in frontend as cookies and was able to make request to server for fetching user details but after implementing register api, i had to change the user model a little bit and after that jwt token is again not being received
> 
> @Anurag-ravi  change the requested I will merge than u can work on that bug again , these are 2 different issue though,
> 

I had one doubt
Now there is no password field so how should i implement login functionality in frontend?
Please elaborate...

**Comment by Anurag-ravi** [comment]
@RupakBiswas-2304 , now should i proceed to work on the bug related to profile details not fetched, as login api is made now?

**Pull request merged**
